// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30JIHlVisCqm8WDp6VyVY2yzYyIa4zpY',
    appId: '1:506447752338:web:a8dfe92dc34b5a1aab0a4b',
    messagingSenderId: '506447752338',
    projectId: 'todo-list-app-ef186',
    authDomain: 'todo-list-app-ef186.firebaseapp.com',
    storageBucket: 'todo-list-app-ef186.firebasestorage.app',
    measurementId: 'G-B5SWZJ0JC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUQKA6KjWMYqJCqS0qm9hLcHCYPF9rT0',
    appId: '1:506447752338:android:7f291ddc20d72fb2ab0a4b',
    messagingSenderId: '506447752338',
    projectId: 'todo-list-app-ef186',
    storageBucket: 'todo-list-app-ef186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZMKbGn12Wk8LUUxJP6sEl64ZjWUE_tE',
    appId: '1:506447752338:ios:7eb83ac0fa8b0887ab0a4b',
    messagingSenderId: '506447752338',
    projectId: 'todo-list-app-ef186',
    storageBucket: 'todo-list-app-ef186.firebasestorage.app',
    iosBundleId: 'com.app.todolist.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZMKbGn12Wk8LUUxJP6sEl64ZjWUE_tE',
    appId: '1:506447752338:ios:7eb83ac0fa8b0887ab0a4b',
    messagingSenderId: '506447752338',
    projectId: 'todo-list-app-ef186',
    storageBucket: 'todo-list-app-ef186.firebasestorage.app',
    iosBundleId: 'com.app.todolist.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB30JIHlVisCqm8WDp6VyVY2yzYyIa4zpY',
    appId: '1:506447752338:web:555f68324176eadeab0a4b',
    messagingSenderId: '506447752338',
    projectId: 'todo-list-app-ef186',
    authDomain: 'todo-list-app-ef186.firebaseapp.com',
    storageBucket: 'todo-list-app-ef186.firebasestorage.app',
    measurementId: 'G-HH77B9LFQC',
  );
}
